# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
